### ISSUE TITLE
lowTemperatureInC is error.

### ISSUE THREAD

**Issue by Whirlwind** [nishanths/YWeatherAPI#2]
There is a error in the method `- (NSDictionary*) packagedYWForecastDayInfoFor:(NSDictionary*)forecastDayInfo temperatureUnit:(YWATemperatureUnit)temperatureUnit`:

```
    NSString* lowTemperatureInC = [NSString stringWithFormat:@"%.2f", [self temperatureIn:C from:F value:[highTemperatureInF doubleValue]]];
```

The `highTemperatureInF` should be `lowTemperatureInF`.

**Comment by nishanths** [comment]
Fixed in version 1.0.6. Thanks for catching this, @Whirlwind!
