### ISSUE TITLE
city/locations search request

### ISSUE THREAD

**Issue by anguskwan** [nishanths/YWeatherAPI#3]
are you planning to provide a api for search cities? returning array of citis, woeid(s) by natural-language.
thanks.

**Comment by nishanths** [comment]
If you want weather conditions by city or WOEID, please see these two methods.
- [allCurrentConditionsForLocation:success:failure:](http://cocoadocs.org/docsets/YWeatherAPI/1.0.4/Classes/YWeatherAPI.html#//api/name/allCurrentConditionsForLocation:success:failure:)
- [allCurrentConditionsForWOEID:success:failure:](http://cocoadocs.org/docsets/YWeatherAPI/1.0.4/Classes/YWeatherAPI.html#//api/name/allCurrentConditionsForWOEID:success:failure:)

You can use "natural language" when specifying the cities, so `Austin`, `Austin Texas`, and `Austin, TX` will work fine.

Is that what you were looking for, or is it something else?
