### ISSUE TITLE
Location should be encoded in querystring

### ISSUE THREAD

**Issue by rahulrawat30101989** [nishanths/YWeatherAPI#4]
Please have a look at my question.

http://stackoverflow.com/questions/37323984/yweatherapi-throws-exception-sometime-for-some-latitude-and-longitude

Probably issue is here. Please look at below url which is trying to be parse.
`https://query.yahooapis.com/v1/public/yql?q=select woeid from geo.places(1) where text='Prince George's MD United States'&format=json`

so i am getting error.

```
error: {
  lang: "en-US",
  description: "Query syntax error(s) [line 1:58 missing EOF at 's']"
}
```

i changed my url. Here only changed happened remove ' quote mark which i got in address. so new url is:

`https://query.yahooapis.com/v1/public/yql?q=select woeid from geo.places(1) where text='Prince Georges MD United States'&format=json`

```
query: {
  count: 1,
  created: "2016-05-19T13:05:54Z",
  lang: "en-GB",
  results: {
    place: {
      woeid: "12588692"
    }
  }
}
```

kindly fix it in api. I really want to use this library.

Thanks nishanths.

**Comment by nishanths** [comment]
@rahulrawat30101989 Thanks for reporting. Will fix soon. 👍

**Comment by rahulrawat30101989** [comment]
Thank you. I will wait :)
